int _putchar(char c);
int print_alphabet();
int main(void);
int print_alphabet_x10(void);
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int _abs(int);
int print_last_digit(int);
int _isupper(int c);
int _isdigit(int c);
int mul(int a, int b);

void jack_bauer(void);
void times_table(void);
void print_numbers(void);
void print_most_numbers(void);
void more_numbers(void);
void print_line(int n);
void print_diagonal(int n);
void print_square(int size);
void print_triangle(int size);
